### ISSUE TITLE
PetSets

### ISSUE THREAD

**Issue by devth** [kelseyhightower/consul-on-kubernetes#1]
Wouldn't PetSets help reduce some of the boilerplate?
- auto provision persistent disks
- single petset configuration instead of 3 deployments

**Comment by sl1pm4t** [comment]
I'm also interested in seeing this updated to PetSets. 
I started to work on a PetSet version, but then found PetSets (alpha feature) is not yet enabled on GKE (my Kubernetes environment of choice).

**Comment by sl1pm4t** [comment]
Nevermind, I just saw #2

**Comment by kelseyhightower** [comment]
StatefulSets are now being used!
