### ISSUE TITLE
Generate TLS Certificates error as must specify -cert or -domain

### ISSUE THREAD

**Issue by ssubramanian123** [kelseyhightower/consul-on-kubernetes#19]
Hi @kelseyhightower 

I am just following the document to deploy consul in k8s cluster. When I try to execute the Generate TLS certificate steps, getting below error.

cfssl gencert -initca ca/ca-config.json | cfssljson -bare ca
Must specify bundle target through -cert or -domain
Failed to parse input: unexpected end of JSON input

Can you please help me what I am missing here?

Thanks,
Sakthi

**Comment by ssubramanian123** [comment]
CC: @blachniet / @jwhitcraft

**Comment by blachniet** [comment]
I think you've got a minor typo in your command. Instead of `ca/ca-config.json`, enter `ca/ca-csr.json`:

    cfssl gencert -initca ca/ca-csr.json | cfssljson -bare ca

Let me know how that works!

**Comment by ssubramanian123** [comment]
I wrongly downloaded cfssl bundle version... I found the correct one and it worked. Thank you for your support.
