### ISSUE TITLE
can't resolve consul-1.consul.$(NAMESPACE).svc.cluster.local when join.

### ISSUE THREAD

**Issue by larrycai** [kelseyhightower/consul-on-kubernetes#22]
I try to follow the guideline to install consul in kubernetes 1.7.5, but it is failure due to can't resolve the hostname `consul-0.consul.$(NAMESPACE).svc.cluster.local`, I use `default` namespace

    kubectl logs consul-0
    ...
    
    2017/11/01 12:48:58 [INFO] consul: Adding LAN server consul-0 (Addr: tcp/10.233.78.176:8300) (DC: dc1)
    2017/11/01 12:48:58 [INFO] agent: Started DNS server 0.0.0.0:8600 (udp)
    2017/11/01 12:48:58 [INFO] agent: Started DNS server 0.0.0.0:8600 (tcp)    2017/11/01 12:48:58 [INFO] agent: (LAN) joining: [consul-0.consul.default.svc.cluster.local consul-1.consul.default.svc.cluster.local consul-2.consul.default.svc.cluster.local]
    2017/11/01 12:48:58 [INFO] agent: Started HTTP server on [::]:8500

    2017/11/01 12:48:58 [INFO] agent: Retry join is supported for: aws azure gce softlayer
    2017/11/01 12:48:58 [INFO] agent: Joining cluster...
    2017/11/01 12:48:58 [WARN] memberlist: Failed to resolve consul-1.consul.default.svc.cluster.local: lookup consul-1.consul.default.svc.cluster.local on 10.233.0.3:53: no such host
    2017/11/01 12:48:58 [WARN] memberlist: Failed to resolve consul-2.consul.default.svc.cluster.local: lookup consul-2.consul.default.svc.cluster.local on 10.233.0.3:53: no such host
    2017/11/01 12:48:58 [INFO] agent: (LAN) joined: 1 Err: <nil>
    2017/11/01 12:48:58 [INFO] agent: Join completed. Synced with 1 initial agents
    2017/11/01 12:49:04 [WARN] raft: no known peers, aborting election

Are there anything I missed to configure in kubernetes or I need extra component there.

**Comment by larrycai** [comment]
I made mistake, I forget to create service in advance: `kubectl create -f services/consul.yaml`

other thing related to my problem
* need prepare 3 PV storage in k8s for 3 consul pods

**Comment by AATHITH** [comment]
For me everything worked fine where I recreated it, consul members refused to join the cluster, I tried creating services first but it didn't help. @larrycai I followed this link [https://testdriven.io/blog/running-vault-and-consul-on-kubernetes/](URL) to create a vault-consul cluster in kubernetes
