### ISSUE TITLE
statefulset Replicas status is desired

### ISSUE THREAD

**Issue by vTNT** [kelseyhightower/consul-on-kubernetes#33]
hi：
    when i run this command: kubectl describe statefulset consul;
    it show that 
   Replicas:           3 desired | 0 total
   Pods Status:        0 Running / 0 Waiting / 0 Succeeded / 0 Failed;
   it didn't create any pods, so how can i solve this problem

**Comment by sl1pm4t** [comment]
are there any consul pods in Pending status?
if so, run `kubectl describe` on one of them to see what error is preventing them being scheduled.

**Comment by vTNT** [comment]
@sl1pm4t  when i run kubectl get po,  i can‘t see any consul pods in pending status

**Comment by vTNT** [comment]
@sl1pm4t i found what happend. run kubectl get events. it show that
create Pod consul-0 in StatefulSet consul failed error: pods "consul-0" is forbidden: SecurityContext.FSGroup is forbidden . 
thank you so much  ^ ^
