### ISSUE TITLE
Error attaching EBS volume ... volume is in "creating" state

### ISSUE THREAD

**Issue by sswainright** [kelseyhightower/consul-on-kubernetes#37]
I have setup and installed this Consul stateful set on another kops cluster and it works fine.  I added a new kops cluster, running the same scripts and the Pods fail to start with:

> pod has unbound PersistentVolumeClaims (repeated 4 times)
> AttachVolume.Attach failed for volume "pvc-b032bc3a-a660-11e8-af7e-06d95e0f9040" : "Error attaching EBS volume \"vol-07968f2e9d0bb523d\"" to instance "i-0f511d8cf681f0fc9" since volume is in "creating" state
> Back-off restarting failed container

Any help would be much appreciated!

**Comment by lukeab** [comment]
Experiencing this also in a normal deployment using helm stable/grafana chart enabling persistence
if i delete the pod and it re-creates it, then get multi attach error with the pvc

**Comment by ailisp** [comment]
Also have this issue running cockroachdb helm chart.

**Comment by sswainright** [comment]
Anyone ever figure out a resolution to this issue?

**Comment by sswainright** [comment]
This no longer seems to be an issue with the latest updates
